<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CategorySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = [
            [
                'name' => 'Sparkling wine',
                'name_uk' => 'IГРИСТЕ ВИНО',
                'slug' => 'sparkling-wine',
                'description' => null,
                'description_uk' => null,
                'icon' => 'bi bi-tag',
                'display_order' => 0,
                'is_active' => 1,
            ],
            [
                'name' => 'Alcoholic cocktails',
                'name_uk' => 'АЛКОГОЛЬНI КОКТЕЙЛI',
                'slug' => 'alcoholic-cocktails',
                'description' => null,
                'description_uk' => null,
                'icon' => 'bi bi-tag',
                'display_order' => 0,
                'is_active' => 1,
            ],
            [
                'name' => 'APERITIF',
                'name_uk' => 'АПЕРИТИВ',
                'slug' => 'aperitif',
                'description' => null,
                'description_uk' => null,
                'icon' => 'bi bi-tag',
                'display_order' => 0,
                'is_active' => 1,
            ],
            [
                'name' => 'NON-ALCOHOLIC DRINKS',
                'name_uk' => 'БЕЗАЛКОГОЛЬНI НАПОI',
                'slug' => 'non-alcoholic-drinks',
                'description' => null,
                'description_uk' => null,
                'icon' => 'bi bi-tag',
                'display_order' => 0,
                'is_active' => 1,
            ],
            [
                'name' => 'WHISKEY',
                'name_uk' => 'ВIСКI',
                'slug' => 'whiskey',
                'description' => null,
                'description_uk' => null,
                'icon' => 'bi bi-tag',
                'display_order' => 0,
                'is_active' => 1,
            ],
            [
                'name' => 'WINES OF ITALY',
                'name_uk' => 'ВИНА IТАЛII',
                'slug' => 'wines-of-italy',
                'description' => null,
                'description_uk' => null,
                'icon' => 'bi bi-tag',
                'display_order' => 0,
                'is_active' => 1,
            ],
            [
                'name' => 'WINES OF GEORGIA',
                'name_uk' => 'ВИНА ГРУЗII',
                'slug' => 'wines-of-georgia',
                'description' => null,
                'description_uk' => null,
                'icon' => 'bi bi-tag',
                'display_order' => 0,
                'is_active' => 1,
            ],
            [
                'name' => 'SIDE DISH',
                'name_uk' => 'ГАРНIР',
                'slug' => 'side-dish',
                'description' => null,
                'description_uk' => null,
                'icon' => 'bi bi-tag',
                'display_order' => 0,
                'is_active' => 1,
            ],
            [
                'name' => 'HOT APPETIZERS',
                'name_uk' => 'ГАРЯЧI ЗАКУСКИ',
                'slug' => 'hot-appetizers',
                'description' => null,
                'description_uk' => null,
                'icon' => 'bi bi-tag',
                'display_order' => 0,
                'is_active' => 1,
            ],
            [
                'name' => 'HOT DRINKS',
                'name_uk' => 'ГАРЯЧI НАПОI',
                'slug' => 'hot-drinks',
                'description' => null,
                'description_uk' => null,
                'icon' => 'bi bi-tag',
                'display_order' => 0,
                'is_active' => 1,
            ],
            [
                'name' => 'HOT DISHES',
                'name_uk' => 'ГАРЯЧI СТРАВИ',
                'slug' => 'hot-dishes',
                'description' => null,
                'description_uk' => null,
                'icon' => 'bi bi-tag',
                'display_order' => 0,
                'is_active' => 1,
            ],
            [
                'name' => 'VODKA',
                'name_uk' => 'ГОРIЛКА',
                'slug' => 'vodka',
                'description' => null,
                'description_uk' => null,
                'icon' => 'bi bi-tag',
                'display_order' => 0,
                'is_active' => 1,
            ],
            [
                'name' => 'DESSERTS',
                'name_uk' => 'ДЕСЕРТИ',
                'slug' => 'desserts',
                'description' => null,
                'description_uk' => null,
                'icon' => 'bi bi-tag',
                'display_order' => 0,
                'is_active' => 1,
            ],
            [
                'name' => 'GIN',
                'name_uk' => 'ДЖИН',
                'slug' => 'gin',
                'description' => null,
                'description_uk' => null,
                'icon' => 'bi bi-tag',
                'display_order' => 0,
                'is_active' => 1,
            ],
            [
                'name' => 'ADD-ONS / EXTRAS',
                'name_uk' => 'ДОДАТКИ',
                'slug' => 'add-ons-extras',
                'description' => null,
                'description_uk' => null,
                'icon' => 'bi bi-tag',
                'display_order' => 0,
                'is_active' => 1,
            ],
            [
                'name' => 'COGNAC',
                'name_uk' => 'КОНЬЯК',
                'slug' => 'cognac',
                'description' => null,
                'description_uk' => null,
                'icon' => 'bi bi-tag',
                'display_order' => 0,
                'is_active' => 1,
            ],
            [
                'name' => 'GRILL / BARBECUE',
                'name_uk' => 'МАНГАЛ',
                'slug' => 'grill-barbecue',
                'description' => null,
                'description_uk' => null,
                'icon' => 'bi bi-tag',
                'display_order' => 0,
                'is_active' => 1,
            ],
            [
                'name' => 'WOOD-FIRED OVEN',
                'name_uk' => 'ПIЧ НА ДРОВАХ',
                'slug' => 'wood-fired-oven',
                'description' => null,
                'description_uk' => null,
                'icon' => 'bi bi-tag',
                'display_order' => 0,
                'is_active' => 1,
            ],
            [
                'name' => 'BEER',
                'name_uk' => 'ПИВО',
                'slug' => 'beer',
                'description' => null,
                'description_uk' => null,
                'icon' => 'bi bi-tag',
                'display_order' => 0,
                'is_active' => 1,
            ],
            [
                'name' => 'RUM',
                'name_uk' => 'РОМ',
                'slug' => 'rum',
                'description' => null,
                'description_uk' => null,
                'icon' => 'bi bi-tag',
                'display_order' => 0,
                'is_active' => 1,
            ],
            [
                'name' => 'SALADS',
                'name_uk' => 'САЛАТИ',
                'slug' => 'salads',
                'description' => null,
                'description_uk' => null,
                'icon' => 'bi bi-tag',
                'display_order' => 0,
                'is_active' => 1,
            ],
            [
                'name' => 'BREAKFAST',
                'name_uk' => 'СНIДАНОК',
                'slug' => 'breakfast',
                'description' => null,
                'description_uk' => null,
                'icon' => 'bi bi-tag',
                'display_order' => 0,
                'is_active' => 1,
            ],
            [
                'name' => 'SAUCES',
                'name_uk' => 'СОУСИ',
                'slug' => 'sauces',
                'description' => null,
                'description_uk' => null,
                'icon' => 'bi bi-tag',
                'display_order' => 0,
                'is_active' => 1,
            ],
            [
                'name' => 'SOUPS',
                'name_uk' => 'СУПИ',
                'slug' => 'soups',
                'description' => null,
                'description_uk' => null,
                'icon' => 'bi bi-tag',
                'display_order' => 0,
                'is_active' => 1,
            ],
            [
                'name' => 'TEQUILA',
                'name_uk' => 'ТЕКIЛА',
                'slug' => 'tequila',
                'description' => null,
                'description_uk' => null,
                'icon' => 'bi bi-tag',
                'display_order' => 0,
                'is_active' => 1,
            ],
            [
                'name' => 'FRESH JUICES',
                'name_uk' => 'ФРЕШI',
                'slug' => 'fresh-juices',
                'description' => null,
                'description_uk' => null,
                'icon' => 'bi bi-tag',
                'display_order' => 0,
                'is_active' => 1,
            ],
            [
                'name' => 'COLD APPETIZERS',
                'name_uk' => 'ХОЛОДНI ЗАКУСКИ',
                'slug' => 'cold-appetizers',
                'description' => null,
                'description_uk' => null,
                'icon' => 'bi bi-tag',
                'display_order' => 0,
                'is_active' => 1,
            ],
            [
                'name' => 'CHACHA',
                'name_uk' => 'ЧАЧА',
                'slug' => 'chacha',
                'description' => null,
                'description_uk' => null,
                'icon' => 'bi bi-tag',
                'display_order' => 0,
                'is_active' => 1,
            ],
        ];

        DB::table('categories')->insert($categories);
    }
}
